### ISSUE TITLE
Develop backend architecture

### ISSUE THREAD

**Issue by comountainclimber** [comountainclimber/rn-task-manager#5]
This task is mostly a placeholder for planning and discussion around the implementation of backend services for `rn-task-manager`. 

After thinking about this over the past few days I think the best solution would be to architect a pub sub architecture that would allow the mobile platform to publish messages to a queue (https://www.rabbitmq.com/ or AWS SQS would be very good options which I am also familiar with). This pattern would allow the mobile app to offload data to the backend system data regardless of whether or not it currently has internet connectivity. Furthermore additional backend microservices could be built out to subscribe to the queue (analytics, whatever materialization we want).

We can use local storage to persist a list a of messages that need to be broadcasted to our backend services, whenever the client has a connection we offload these as a background job client side with essentially no noticeable effect on performance/UX.

We can also expose an API for the mobile platform which will allow the mobile client  to "sync" should we develop additional products for the platform (web, desktop applications) although this particular piece is definitely a future enhancement beyond the scope of this issue.

**Comment by bone-saw** [comment]
I gave Ashu and Bruno a heads up to read over this before our call tomorrow (in Slack, can't @mention them in here, oddly). They will have better insight than myself here.
